/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ModelId = IDL.Text;
export const ModelInferenceArtifact = IDL.Vec(IDL.Nat8);
export const Model = IDL.Record({
  'id' : ModelId,
  'totalInferenceCount' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'artifact' : IDL.Opt(ModelInferenceArtifact),
  'lastInferenceTime' : IDL.Int,
  'timestamp' : IDL.Int,
  'payloadSize' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ModelMetadataUpdate = IDL.Record({
  'id' : ModelId,
  'name' : IDL.Text,
  'artifact' : IDL.Opt(ModelInferenceArtifact),
  'payloadSize' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteModel' : IDL.Func([ModelId], [], []),
  'getAdminModels' : IDL.Func([], [IDL.Vec(Model)], ['query']),
  'getAvailableModels' : IDL.Func([], [IDL.Vec(Model)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getModelById' : IDL.Func([ModelId], [IDL.Opt(Model)], ['query']),
  'getModelStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalInferenceCount' : IDL.Nat,
          'totalStorageUsed' : IDL.Nat,
          'totalModels' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMostPopularModels' : IDL.Func([IDL.Nat], [IDL.Vec(Model)], ['query']),
  'getMyModels' : IDL.Func([], [IDL.Vec(Model)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateModelMetadata' : IDL.Func([ModelMetadataUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ModelId = IDL.Text;
  const ModelInferenceArtifact = IDL.Vec(IDL.Nat8);
  const Model = IDL.Record({
    'id' : ModelId,
    'totalInferenceCount' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'artifact' : IDL.Opt(ModelInferenceArtifact),
    'lastInferenceTime' : IDL.Int,
    'timestamp' : IDL.Int,
    'payloadSize' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ModelMetadataUpdate = IDL.Record({
    'id' : ModelId,
    'name' : IDL.Text,
    'artifact' : IDL.Opt(ModelInferenceArtifact),
    'payloadSize' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteModel' : IDL.Func([ModelId], [], []),
    'getAdminModels' : IDL.Func([], [IDL.Vec(Model)], ['query']),
    'getAvailableModels' : IDL.Func([], [IDL.Vec(Model)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getModelById' : IDL.Func([ModelId], [IDL.Opt(Model)], ['query']),
    'getModelStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalInferenceCount' : IDL.Nat,
            'totalStorageUsed' : IDL.Nat,
            'totalModels' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMostPopularModels' : IDL.Func([IDL.Nat], [IDL.Vec(Model)], ['query']),
    'getMyModels' : IDL.Func([], [IDL.Vec(Model)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateModelMetadata' : IDL.Func([ModelMetadataUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };